### ISSUE TITLE
Cant Reset PC | Restore Point | I dont have USB

### ISSUE THREAD

**Issue by AnonLeonidas** [ionuttbara/melody_windows#24] opened 2024-04-05 13:39 UTC
Hi, my name is Ares

I have this problem, normally I wouldn't want to reset my PC because I think this optimization is very good for both Performance and Latency, but the problem is that it has problems...

1. I can't reset my pc | When i click on Reset This PC I Click Delete Everything it ask me 

2. Restore point doesn't work | Even though I turned on all the necessary Services and edited the Registry

3. Sfc /scannow or DISM /Online /Cleanup-Image /Restorehealth

4. Advanced Startup Options Missing System Recovery Options

5. Video Editors like CapCut don't work as they should, and that's not good for Creator and Editor like me

6. The animation when you CTRL It's useless, at first it's fun but then it annoys you

7. You delete Quick Access and then you have to go through the whole Disk to find "Downloads"

This was Translated with Deepl. But not this below.

I recommended this Optimization to my friend, and what happend is crazy, he have 1 GPU Intel 2 GPU AMD (He is on notebook)
After Restart his pc started Randomly Shut Down, when i tell him look to the Task Manager CPU was On 0.38 Ghz
I dont even know how to fix it, this is crazy, cause he cant even Reset Pc from Restore Point cause Now Work and Cant even do shit when hes pc turn off in minute.

Thats all problems, but the optimization is really good, if someone tryna help us comment down be low.

Thanks, Ares
![image](https://github.com/ionuttbara/melody_windows/assets/158764179/442a2b3e-6a09-4504-af86-f2bd4b35609b)

**Comment by velaar** [comment] 2024-04-05 22:19
You should [make windows USB](https://support.microsoft.com/en-us/windows/create-installation-media-for-windows-99a58364-8c02-206f-aa6f-40c3b507420d) and reinstall. Otherwise stock laptops have recovery partitions and procedures in the manuals related to them. @ionuttbara  - Do you think a bigger warning of caution will help? Experienced users only? Backups strongly suggested?

**Comment by ionuttbara** [comment] 2024-05-08 23:23
closed this issue due its duplicate of #5

**Closed by ionuttbara** 2024-05-08 23:23 UTC
